### ISSUE TITLE
glue.css fail to load

### ISSUE THREAD

**Issue by betterclever** [khanhas/genius-spicetify#11]
The url fails to resolve
`https://local_resource_host/css/glue.css net::ERR_NAME_NOT_RESOLVED`

![image](https://user-images.githubusercontent.com/16309034/84602850-d08e9c80-aea7-11ea-86ce-3ab4078813a1.png)

OS: Arch Linux
Spotify Installation: AUR
Spicetify Installation: AUR
Spicetify version: 0.9.9
Spotify version: 1:1.1.10.546-4

**Comment by khanhas** [comment]
Upgrade your spotify

**Comment by betterclever** [comment]
what is the minimum supported version for this? I see the above one as the current latest version on AUR

**Comment by khanhas** [comment]
https://aur.archlinux.org/packages/spotify-dev/
