### ISSUE TITLE
After updating, there's no colorful background

### ISSUE THREAD

**Issue by jimao233** [khanhas/genius-spicetify#14]
Any way to get it back? I only found how to turn it off: https://github.com/khanhas/genius-spicetify/issues/6

**Comment by khanhas** [comment]
Ehh sorry, I virtually hate it so much so I removed it

**Comment by jimao233** [comment]
The problem is that the lyrics now is grey, not bright enough to see in the dark background.
![20200728115836](https://user-images.githubusercontent.com/24926585/88617877-3b97d980-d0ca-11ea-9f38-0da97e5f6eda.png)

**Comment by khanhas** [comment]
Add this to your user.css:
```css
.lyrics-lines-container, .message-container {
    color: #FFFFFF;
}
```
or edit lyrics.css directly, at line 13:
```
    color: var(--modspotify_secondary_fg);
```
to
```
    color: #FFFFFF;
```

**Comment by jimao233** [comment]
Unsynced lyrics of Genius is now all white, but synced lyrics of Genius and Musixmatch is still grey...
![微信截图_20200728164944](https://user-images.githubusercontent.com/24926585/88641943-6e55c800-d0f2-11ea-9ea8-0a8358ec2a0e.png)
![微信截图_20200728164641](https://user-images.githubusercontent.com/24926585/88641949-6f86f500-d0f2-11ea-9799-59af60fa27bd.png)
![微信截图_20200728164655](https://user-images.githubusercontent.com/24926585/88641956-7281e580-d0f2-11ea-9e9a-86a5cf5255f3.png)

**Comment by khanhas** [comment]
Oh my bad.
Just do the same thing with `.lyrics-lines-container .lyrics-list-animated .lyrics-line`

**Comment by jimao233** [comment]
It works! Thank you so much!
