### ISSUE TITLE
Genius: Not the full lyrics

### ISSUE THREAD

**Issue by nils-kt** [khanhas/genius-spicetify#16]
Hi,
for me the Genius Tab never shows the whole lyrics of a song.
When I check the lyrics on Genius itself, all the lyrics are there.

**Comment by stankovictab** [comment]
I can confirm that I have the same issue. Musixmatch works flawlessly though.

**Comment by nils-kt** [comment]
Nothing has changed for me.

**Comment by khanhas** [comment]
Sorry for late reply, I just saw what was wrong and fixed in latest commit.
Please git pull

**Comment by nils-kt** [comment]
Now it works! Sorry for the late answer.
