### ISSUE TITLE
Recently synced lyrics can't be shown

### ISSUE THREAD

**Issue by ajiou** [khanhas/genius-spicetify#17]
If a song just been synced from Musixmatch desktop app, the lyrics can't be fetched.

**Comment by khanhas** [comment]
Sorry, I don't understand the problem.

**Comment by ajiou** [comment]
simply put, some lyrics can't be fetch
![2020-09-02_220039](https://user-images.githubusercontent.com/35028055/91993330-d3db4b00-ed67-11ea-8f3a-8284e91594cc.png)
while Musixmatch app can
![2020-09-02_220226](https://user-images.githubusercontent.com/35028055/91995472-73014200-ed6a-11ea-9433-b5c5597fc60c.png)

**Comment by khanhas** [comment]
Since you already had Musicxmatch, can you follow instructions on readme page to get your personal `UserToken` and try again?

**Comment by ajiou** [comment]
Sorry, but i've already set the UserToken.

btw, i'm trying to fix it myself, but it takes some time to read through the code.

**Comment by khanhas** [comment]
Have you tried with default UserToken?
You can try mine:
```
2005218b74f939209bda92cb633c7380612e14cb7fe92dcd6a780f
```

**Comment by ajiou** [comment]
Thanks, It's working.

but it's kinda weird though...
