### ISSUE TITLE
Symlinks Issue: error Custom app "genius" not found.

### ISSUE THREAD

**Issue by 3raxton** [khanhas/genius-spicetify#2]
Glad to see this released! Currently, I'm having issues installing the custom app. Below is the output I get from running the command in terminal.

One thing to note: I don't understand how to accurately replace the directory name in the Bash command for Mac. 

```cd "$(dirname "$(spicetify -c)")/CustomApps"```

Instead, I CDed into the spicetify folder and used the clone command within the CustomApps folder. Do I need to remove the $ and keep the parenthesis, or is there something else I'm missing?

Here is the output that I got from running ```mv "genius-spicetify" genius```

```spicetify v0.9.9
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
OK
Transferring extensions:
OK
Creating custom apps symlinks:
error Custom app "genius" not found.
OK
success Spotify is spiced up!
```

![image](https://user-images.githubusercontent.com/20716142/81256105-13ca3580-8ff5-11ea-9945-c6ced5257c00.png)

**Comment by 3raxton** [comment]
I've got this working by putting it into the spicetify_data folder in my directory. Is there a better way to approach this?

![image](https://user-images.githubusercontent.com/20716142/81257256-6527f400-8ff8-11ea-94df-b323aa665f15.png)

**Comment by khanhas** [comment]
I guess you did it correctly. If you don't have a custom config folder, by default, the command `cd "$(dirname "$(spicetify -c)")/CustomApps"` would change directory to `~/spicetify_data/CustomApps`.
From there, you clone the repo and change just cloned folder name to `genius`.

**Comment by 3raxton** [comment]
Thanks for letting me know; that certainly helps. I appreciate your inclusion of a key in the code for Musixmatch as well. That’s incredibly helpful!

**Comment by khanhas** [comment]
All good! I'm glad you're having fun with spicetify.

**Comment by 3raxton** [comment]
Honestly one of the best things to happen to my Mac. Don't think I could live without it! Thanks for putting in the work to make it this great.
