### ISSUE TITLE
Is there any way to get no uglified code?

### ISSUE THREAD

**Issue by sherlockheine** [khanhas/genius-spicetify#20]
I'm going to do some changes but it's really difficult to do them in uglified code. Would you like to share source code or is there any place I can find it? Thanks!

**Comment by khanhas** [comment]
I don't think anyone can access in source code except Spotify Development team.
What you want to change? UI or app functionalities?

**Comment by sherlockheine** [comment]
Understood. I want to improve the way lyrics displayed + add new features. In that case I will do my own spicetify app.

Thank you a lot for such a great tool! It's really awesome!
