### ISSUE TITLE
Genius lyrics that are built in to spotify doesn't show lyrics

### ISSUE THREAD

**Issue by SaruDesu422** [khanhas/genius-spicetify#21]
![image](https://user-images.githubusercontent.com/51990168/97408717-13b94b80-192f-11eb-8217-d03c98420513.png)

**Comment by khanhas** [comment]
Where did you open Lyric app?
From sidebar or player bar?

**Comment by SaruDesu422** [comment]
![image](https://user-images.githubusercontent.com/51990168/97409257-e325e180-192f-11eb-8b36-dcc3a6f19989.png)

**Comment by SaruDesu422** [comment]
the key button

**Comment by khanhas** [comment]
That wouldn't work, it's not this project is for.
Please follow instruction on the README page and access my lyric app on sidebar.

**Comment by SaruDesu422** [comment]
alrite thx

**Comment by SaruDesu422** [comment]
![image](https://user-images.githubusercontent.com/51990168/97411373-c212c000-1932-11eb-854b-0de2a087b7ba.png)
my musixmatch doesnt look the same as the one from readme page, and when i press ctrl+shift+i, nth happens

**Comment by khanhas** [comment]
It only works with Musixmatch installed from Windows Store

**Comment by SaruDesu422** [comment]
ohh i see, thx
