### ISSUE TITLE
Genius doesn't autoscroll and Musixmatch doesnt freely scroll

### ISSUE THREAD

**Issue by UnlimitedCookies** [khanhas/genius-spicetify#22]
Are these constraints by purpose or restricted due to the upstream providers?

Further, why does Musixmatch only show the current and next two lines?

**Comment by khanhas** [comment]
Genius doesn't provide timestamp metadata, Musixmatch does.

**Comment by UnlimitedCookies** [comment]
That's what I thought. Would it be possible to enable or disable
auto-scrolling in musixmatch then?

**Comment by khanhas** [comment]
Sorry, there's none.
Please use Genius if you don't want autoscroll.

**Comment by UnlimitedCookies** [comment]
Ok then, thanks for maintaining this awesome software!
