### ISSUE TITLE
Genius Lyrics Custom App

### ISSUE THREAD

**Issue by reero7** [khanhas/genius-spicetify#23]
So im actually confused. When I run the code in the powershell, it doesnt work, I get this huge error. I wasn't getting the git, so I tried the alternate code and this is what I got: 
![Screenshot 2020-12-09 124131](https://user-images.githubusercontent.com/41528809/101666251-f68e9700-3a1b-11eb-9256-deb3b6b6e096.png)

What do I gotta do to make it work?

**Comment by khanhas** [comment]
Yeah sorry, I fixed the commands. Please copy and paste again.

**Comment by reero7** [comment]
Can you send the command here so I am copying the right commands?

**Comment by reero7** [comment]
Ahhhh works now! Thank you so much!
