### ISSUE TITLE
Musixmatch Usertoken for Non-Microsoft Store version.

### ISSUE THREAD

**Issue by dalcop** [khanhas/genius-spicetify#28]
how to get devtools for non-microsoft store version Musixmatch app (downloaded from https://download-app.musixmatch.com/download and installed) to get the `Usertoken` .

**Comment by khanhas** [comment]
You can't, sorry. They are not the same and non-windows store doesn't have devtool to get token.

**Comment by dalcop** [comment]
gotcha, ty.
