### ISSUE TITLE
The lyrics are still unavailable

### ISSUE THREAD

**Issue by nicolaskelvin123** [khanhas/genius-spicetify#29]
Hey, I'm using Spotify for windows and Dribbblish theme with Beach Sunset color scheme. It looks like the lyrics are still not available.
![image](https://user-images.githubusercontent.com/75967348/107019825-1acce100-67dd-11eb-8a19-15ceac5486eb.png)

I also received the error messages in the DevTool 
![image](https://user-images.githubusercontent.com/75967348/107019951-3e902700-67dd-11eb-8e63-36a73c2f6ca2.png)

**Comment by khanhas** [comment]
Lyrics app is not Genius app.
