### ISSUE TITLE
Nothing on Genius page

### ISSUE THREAD

**Issue by holoitsme** [khanhas/genius-spicetify#3]
Hi, I followed the instructions in the readme to set up genius in spicetify-cli. I get no errors during the process but when I open the genius app nothing appears. I'm on Manjaro GNOME with latest stable packages and Spotify installed via flatpak.

![genius page screen](https://user-images.githubusercontent.com/35468654/81477478-40aa6280-9218-11ea-8648-eecbd50f1038.png)

**Comment by khanhas** [comment]
Can you restart Spotify then open DevTool Console, see if there is any error.

**Comment by holoitsme** [comment]
I started Spotify, opened DevTool Console then opened genius app. It shows me four warnings, three of which seem to be related to genius app. I'll attach a screen 


![genius app warnings](https://user-images.githubusercontent.com/35468654/81478126-84eb3200-921b-11ea-9730-2cf8c6209c8c.png)

**Comment by khanhas** [comment]
I installed `spotify-dev` package which is v1,26 right now so version is not problem. Also these warnings are harmless, they won't stop app from loading.
Can you open Spotify director, go to `Apps` folder and check if there is `genius` symlink there? And does it lead to correct folder?

**Comment by holoitsme** [comment]
I confirm that genius symlink is there and it seems to point to the right folder. Screenshot attached

![genius symlink](https://user-images.githubusercontent.com/35468654/81507658-28614300-92ff-11ea-8963-d00af4bb58d6.png)

**Comment by holoitsme** [comment]
Sorry for double posting, just wanted to report that I installed the aur version (spotify-dev, so same Spotify version as you already stated before) and this custom app works just fine on it. Maybe it's something related to flatpak confinement? Don't know, by the way I'm available for testing if you have any idea .

**Comment by khanhas** [comment]
I think that could be it, flatpak prevents programs to access stuff outside of its directory. That's why Spotify could not use the symlink to custom apps spicetify puts in there

**Comment by khanhas** [comment]
I will add an option to copy custom apps instead of symlinks.

**Comment by swingcake** [comment]
> Hi, I followed the instructions in the readme to set up genius in spicetify-cli. I get no errors during the process but when I open the genius app nothing appears.

@khanhas Same issue on WIndows 10.

**Comment by khanhas** [comment]
@swingcake fixed in latest commit. Please `git pull` to update

**Comment by swingcake** [comment]
@khanhas I `git pull`, do I need to `spicetify apply` or simply restart Spotify or does it work on-the-fly?

Also;
> ..I applied Dribbblish theme, and Genius page is no longer blank. It displays the lyrics now but is static (does not highlight the current line). I don't know if that's the intended behaviour.
> 
> I think it has something to do with the following command:
> `spicetify config inject_css 1 replace_colors 1 overwrite_assets 1`

Comments on this?

Thanks

**Comment by stankovictab** [comment]
It just started working for me by doing `spicetify apply` and `spicetify update`, did not need to pull

**Comment by holoitsme** [comment]
By the way, my issue was different. When I wrote 
> when I open the genius app nothing appears. 
I meant the whole app, including musixmatch. Clicking on "Genius" in the sidebar resulted in a blank screen and I couldn't even choose Genius or Musixmatch. 
The issue I had is probably related to flatpak confinement, because installing from AUR everything is fine. 
I think flatpak issue requires a change on spicetify app, but just a guess.

**Comment by khanhas** [comment]
@holoitsme I wrote a guide to overriding flatpak filesystem. If you have time, can you try it out:
https://github.com/khanhas/spicetify-cli/wiki/Guide-for-Flatpak-user#using-custom-apps-and-node_modules
If this works, I don't I need to change anything on spicetify, less hairy code.

**Comment by holoitsme** [comment]
@khanhas sorry for the late response, I just tried and it works perfectly! Congrats!
