### ISSUE TITLE
always white lyrics

### ISSUE THREAD

**Issue by dmhd6219** [khanhas/genius-spicetify#35]
i have white lyrics in genius and unsynced musixmatch. changing all colors params in style.css does nothing

**Comment by khanhas** [comment]
I don't know how I suppose to support this since this is not a genius app problem.
You said "white lyric" and I suppose to guess your background is also white and you can't see them?
Variable for lyric color is `secondary_fg`. Change it in your spicetify theme "color.ini"

**Comment by dmhd6219** [comment]
yes, my bg is also white, but secondary_fg isnt. i tried to change everything before i wrote this

if you think thats not problem in genius app, i will search anywhere else. thanks
