### ISSUE TITLE
Compatibility problem with extension

### ISSUE THREAD

**Issue by vescgi** [khanhas/genius-spicetify#38]
Hey, I have an extension that removes all the google tracking from Spotify and I'm pretty sure it's interfering with the genius app that doesn't work when I have the extension enabled. Which links should I whitelist from it to solve the problem?
I already tried with genius.com and apic-desktop.musixmatch.com but I keep getting error messages

**Comment by khanhas** [comment]
Sorry, I don't know, seems like it's more of your extension problem than genius app, maybe you blocked certain API. Plus I try my best not to interfere with Spotify money making so I can't help you further.
