### ISSUE TITLE
error: Custom app genius does not have index.js

### ISSUE THREAD

**Issue by for3ever** [khanhas/genius-spicetify#44]
I have a problem using genius-spicetify in the spotify app, which it perfectly installs fine but has a problem when I try to look up for the lyrics. The Genius page won't load, and I tried to reinstall the package and now I get the error at the 'creating custom app symlinks' phase that the custom app genius does not have index.js. Will there be any further updates to fix this error or any solutions to make my spotify app completely fine?

**Comment by khanhas** [comment]
Read release note
