### ISSUE TITLE
add the option to disable background colors

### ISSUE THREAD

**Issue by 3l0w** [khanhas/genius-spicetify#6]
Hi thanks for this nice app.

But the background colors of `lyrics-color-container` is in my case pretty ugly.
![image](https://user-images.githubusercontent.com/37798980/83140452-65467b80-a0ee-11ea-8d2a-48cbbfb9c1eb.png)

Your main js file is bundle i can't modify it to set the background to transparent.
If you can send me the js file no minified or with the background color set to transparent.

**Comment by stankovictab** [comment]
That would be a nice addon, however you could actually do this by overriding the lyrics.css file, by typing in `background-color: yourcolor !important;` in the `lyrics-color-container` class, that worked for me.

**Comment by khanhas** [comment]
Solved then. Just do as stankovictab said.
```css
.lyrics-color-container {
    background-color: transparent !important;
}
```
I would rather put it in `user.css` than modify `lyric.css`.
